### ISSUE TITLE
File set incomplete 

### ISSUE THREAD

**Issue by pieterjanvz** [mr-manuel/venus-os_ngrok#3]
![IMG_5221](https://github.com/mr-manuel/venus-os_ngrok/assets/81514282/876dbdf4-9027-4c85-a876-0ff74a6fd16c)

**Comment by mr-manuel** [comment]
Which Venus OS are you using?

**Comment by mr-manuel** [comment]
I fixed it in the same version. Please hit the download and install button again.

**Comment by pieterjanvz** [comment]
3.00 (stable) on raspberry pi 3b

Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: Manuel ***@***.***>
Verzonden: Sunday, June 18, 2023 4:51:17 PM
Aan: mr-manuel/venus-os_ngrok ***@***.***>
CC: pieterjanvz ***@***.***>; Author ***@***.***>
Onderwerp: Re: [mr-manuel/venus-os_ngrok] File set incomplete (Issue #3)


Which Venus OS are you using?

**Comment by pieterjanvz** [comment]
i had no access to ssh(was not at the boat) but now with logs , error is still there , also tried manual downloading:

2023-06-25 13:36:58.097002500 venus-os_ngrok/setup: --- starting setup script v0.0.4
2023-06-25 13:36:58.238786500 venus-os_ngrok/setup: creating file set for v3.00
2023-06-25 13:36:58.553664500 venus-os_ngrok/setup: installing venus-os_ngrok files
2023-06-25 13:36:58.647062500 venus-os_ngrok/setup: ERROR: no replacement file for PageSettingsServicesNgrok.qml
2023-06-25 13:36:58.700140500 venus-os_ngrok/setup: Downloading ngrok and extracting it
2023-06-25 13:37:05.963946500 venus-os_ngrok/setup: installing venus-os_ngrok service
2023-06-25 13:37:11.103781500 venus-os_ngrok/setup: service venus-os_ngrok running
2023-06-25 13:37:11.112639500 venus-os_ngrok/setup: ++ venus-os_ngrok installed
2023-06-25 13:37:11.178215500 venus-os_ngrok/setup: removing venus-os_ngrok service
2023-06-25 13:37:11.215806500 venus-os_ngrok/setup: ++ venus-os_ngrok uninstalled
2023-06-25 13:37:11.251328500 venus-os_ngrok/setup: installation failed - package uninstalled - exiting

**Comment by mr-manuel** [comment]
Please remove the package completele (remove button) and then download and install it again. Probably there is still the leftover file that is not deleted. Else you can delete the folder over SSH.

```bash
rm -rf /data/venus-os_ngrok
```

**Comment by pieterjanvz** [comment]
Done that , its not working

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: ***@***.***>
Verzonden: zondag 25 juni 2023 18:15
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [mr-manuel/venus-os_ngrok] File set incomplete (Issue #3)


Please remove the package completele (remove button) and then download and install it again. Probably there is still the leftover file that is not deleted. Else you can delete the folder over SSH.

rm -rf /data/venus-os_ngrok

**Comment by mr-manuel** [comment]
I opened an issue in https://github.com/kwindrem/SetupHelper/issues/52 for more informations.

**Comment by mr-manuel** [comment]
Could you please try the latest version?

**Comment by pieterjanvz** [comment]
Thanks , V0.0.5 is working !!

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows

Van: ***@***.***>
Verzonden: dinsdag 4 juli 2023 09:44
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [mr-manuel/venus-os_ngrok] File set incomplete (Issue #3)


Closed #3<https://github.com/mr-manuel/venus-os_ngrok/issues/3> as completed.
